---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache pacjage
      apt:
        name: apache2
        state: latest

    - name: restart apache service
      service:
        name: apache2
        state: restarted

    - name: add php
      apt:
        name: libapache2-mod-php
        state: latest

