---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index
      tags: always
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: websrv
  become: true
  tasks:
    - name: install apache2 and php packages
      tags: apache,apache2,Ubuntu
      apt:
        name: 
          - apache2
          - libapache2-mod-php  
        state: latest

    - name: copy apache default file to dist
      tags: apache,apache2,Ubuntu
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: restart apache service
      service:
        name: apache2
        state: restarted

